# Generated by Django 5.1.7 on 2025-05-24 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0004_booking_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_products', to='farmerapp.booking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmerapp.product')),
            ],
        ),
    ]
