# Generated by Django 5.1.7 on 2025-05-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0006_farmer_alter_booking_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='farmer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
