# Generated by Django 5.1.7 on 2025-05-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0007_alter_booking_farmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='farmer',
        ),
    ]
